### ISSUE TITLE
Docs should indicate that `UseDefaultCredentials` is required for IWA to work

### ISSUE THREAD

**Issue by johnterickson** [MicrosoftDocs/microsoft-authentication-library-dotnet#101]
This API gives the user the ability to provide a `HttpClientFactory` but the docs do not indicate that the created `HttpClient` must have an `HttpClientHandler` with `UseDefaultCredentials` set to `true` in order for IWA to work (as noted in MSAL source code: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/e15befb5f0a6cf4757c5abcaa6487e28e7ebd1bb/src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/SimpleHttpClientFactory.cs#LL26C1-L27C73)

We hit a regression because of this: https://github.com/microsoft/artifacts-credprovider/pull/414

cc @johnschmeichel

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b87a3cd0-2b18-09ee-743d-85b1b34b3891
* Version Independent ID: b87a3cd0-2b18-09ee-743d-85b1b34b3891
* Content: [BaseAbstractApplicationBuilder&lt;T&gt;.WithHttpClientFactory Method (Microsoft.Identity.Client) - Microsoft Authentication Library for .NET](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.baseabstractapplicationbuilder-1.withhttpclientfactory?view=msal-dotnet-latest&source=docs#microsoft-identity-client-baseabstractapplicationbuilder-1-withhttpclientfactory(microsoft-identity-client-imsalhttpclientfactory))
* Content Source: [dotnet/xml/Microsoft.Identity.Client/BaseAbstractApplicationBuilder`1.xml](https://github.com/MicrosoftDocs/microsoft-authentication-library-dotnet/blob/live/dotnet/xml/Microsoft.Identity.Client/BaseAbstractApplicationBuilder`1.xml)
* Service: **active-directory**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dmwendia**

**Comment by localden** [comment]
Covered in: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4158
