### ISSUE TITLE
Links broken in powershell-support.md

### ISSUE THREAD

**Issue by pabrams** [MicrosoftDocs/microsoft-authentication-library-dotnet#316]
The following are broken in the above-indicated file:
[Microsoft Graph PowerShell SDK](https://github.com/MicrosoftDocs/microsoft-authentication-library-dotnet/blob/main/powershell/microsoftgraph/get-started)
[Azure PowerShell SDK](https://github.com/MicrosoftDocs/microsoft-authentication-library-dotnet/blob/main/powershell/azure/new-azureps-module-az)

I glanced at the open link-checker issues and didn't see these flagged in there. Maybe they are part of the exclusions, or it's possible it's in there and I just didn't spend enough time looking.

**Comment by pmaytak** [comment]
Links work. Perhaps was a transient issue.
