### ISSUE TITLE
 Typo in the code example.

### ISSUE THREAD

**Issue by sfusinaz** [MicrosoftDocs/microsoft-authentication-library-dotnet#375]
Typo in the code example.

```
static async Task GetATokenForGraph()
{
    string authority = "https://login.microsoftonline.com/contoso.com";
    string[] scopes = new string[]
    {
        "user.read"
    };

    IPublicClientApplication app;
    app = PublicClientApplicationBuilder.Create(clientId).WithAuthority(authority).Build();

    var accounts = await app.GetAccountsAsync();
    AuthenticationResult result = null;

    if (accounts.Any())
    {
        result = await app.AcquireTokenSilent(scopes, accounts.FirstOrDefault()).ExecuteAync();
    }
```

The last call to AcquireTokenSilent is missing an "s" to "Async". Should be:

`        result = await app.AcquireTokenSilent(scopes, accounts.FirstOrDefault()).ExecuteAsync();`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd6524e-47b3-f667-f060-6da3c2c02962
* Version Independent ID: 9cd6524e-47b3-f667-f060-6da3c2c02962
* Content: [Username and password (ROPC) authentication with MSAL.NET - Microsoft Authentication Library for .NET](https://learn.microsoft.com/en-us/entra/msal/dotnet/acquiring-tokens/desktop-mobile/username-password-authentication)
* Content Source: [msal-dotnet-articles/acquiring-tokens/desktop-mobile/username-password-authentication.md](https://github.com/MicrosoftDocs/microsoft-authentication-library-dotnet/blob/live/msal-dotnet-articles/acquiring-tokens/desktop-mobile/username-password-authentication.md)
* Service: **msal**
* GitHub Login: @localden
* Microsoft Alias: **ddelimarsky**

**Comment by localden** [comment]
Thank you for the report, @sfusinaz - this should be going out in a fix in a few minutes.
